trigger:
- master

resources:
- repo: self

variables:
  tag: latest #'$(Build.BuildId)'


#build image and publish artifacts
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
       name: selfwindowsagent
       demands:
       - agent.name -equals SREE-PC
    steps:
   #- task: Docker@2
   #   inputs:
    #    containerRegistry: 'dockerhubconnection'
     ##  command: 'buildAndPush'
       # Dockerfile: '**/Dockerfile'
      #  tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
    - job: Deploy
      displayName: Deploy
      pool:
        name: selfwindowsagent
        demands:
        - agent.name -equals SREE-PC 
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          itemPattern: '**/*.yaml'
          targetPath: '$(System.ArtifactsDirectory)'
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'kubernetesconnection'
          namespace: 'default'
          manifests: '$(System.ArtifactsDirectory)/projects/microservices/01-currency-exchange-microservice-basic/configuration/kubernetes/deployment.yaml'
          containers: 'srikanthpoosal/devopsrepo:$(tag)'